services:
  redis_server:
    build:
      context: .
      dockerfile: dockerfile_dev
      target: redis_prod
    image: fairway_redis
    container_name: fairway_redis_ct
    hostname: redis
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    expose:
      - "6379"
    networks:
      - fairway-app-network

  backend:
    build:
      context: .
      dockerfile: dockerfile_dev
      target: backend
    image: fairway_backend
    container_name: fairway_backend_ct
    volumes:
      - ./backend:/app
      - ./configs:/configs
      - ../Data/Logs:/var/logs
      - ../Data/Feedbacks:/app/data
    depends_on:
      - redis_server
    env_file: "./backend/.env"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - fairway-app-network
    expose:
      - "8000"

  # Celery Workers
  celery_workers:
    build:
      context: .
      dockerfile: dockerfile_dev
      target: celery
    image: fairway_celery_workers
    container_name: fairway_celery_ct
    volumes:
      - ./backend:/app
      - ./configs:/configs
      - ../Data/Logs:/var/logs
    depends_on:
      - redis_server
      - backend
    networks:
      - fairway-app-network

  # TODO: Handle this later on
  # flower:
  #   volumes:
  #     - ./backend:/app
  #   ports:
  #     - "5555:5555"
  #   depends_on:
  #     - redis_server
  #   command: ["celery", "-A", "celery_tasks.cel", "flower", "--loglevel=info"]

  # Frontend vuejs application
  frontend_server:
    build:
      context: .
      dockerfile: dockerfile_dev
      target: frontend_server
    image: fairway_frontend
    container_name: fairway_frontend_ct
    volumes:
      - ./configs:/configs
    depends_on:
      - backend
      - redis_server
      - celery_workers
    ports:
      - "80:80"
    networks:
      - fairway-app-network

networks:
  fairway-app-network:
    external: false
    driver: bridge