services:
  redis_server:
    build:
      context: .
      dockerfile: dockerfile_prod
      target: redis_prod
    image: fairway_redis
    container_name: fairway_redis_ct
    restart: unless-stopped
    hostname: redis
    volumes:
      # Direct bind read-only mount for config
      - ./redis.conf:/usr/local/etc/redis/redis.conf:ro
      # Named Mount for Data
      - redis_data:/data
    expose:
      - "6379"
    networks:
      - fairway-app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 8s
      retries: 10
      start_period: 4s

  backend:
    build:
      context: .
      dockerfile: dockerfile_prod
      target: backend
    image: fairway_backend
    container_name: fairway_backend_ct
    restart: unless-stopped
    volumes:
      - ./backend:/app
      - ./configs:/configs
      - backend_logs:/var/logs
      - feedback_data:/app/data
    depends_on:
      redis_server:
        condition: service_healthy
    env_file: "./backend/.env"
    networks:
      - fairway-app-network
    expose:
      - "8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      timeout: 15s
      retries: 5
      start_period: 8s
      interval: 45s

  # Celery Workers
  celery_workers:
    build:
      context: .
      dockerfile: dockerfile_prod
      target: celery
    image: fairway_celery_workers
    container_name: fairway_celery_ct
    restart: unless-stopped
    volumes:
      - ./backend:/app
      - ./configs:/configs
      - celery_logs:/var/logs
    depends_on:
      redis_server:
        condition: service_healthy
      backend:
        condition: service_healthy
    networks:
      - fairway-app-network

  frontend_server:
    build:
      context: .
      dockerfile: dockerfile_prod
      target: frontend_server
    image: fairway_frontend
    container_name: fairway_frontend_ct
    volumes:
      - ./configs:/configs
    depends_on:
      backend:
        condition: service_healthy
      redis_server:
        condition: service_healthy
      celery_workers:
        condition: service_started
      fairway_ollama:
        condition: service_started
    ports:
      - "8011:80"
    networks:
      - fairway-app-network

  # Important NOTE:- If the models aren't downloaded, simply start ONLY this service and the models will be downloaded
  fairway_ollama:
    build:
      context: .
      dockerfile: dockerfile_prod
      target: ollama_server
    image: fairway_ollama
    container_name: fairway_ollama_ct
    volumes:
      - ../Data/.ollama:/root/.ollama
    restart: unless-stopped
    expose:
      - "11434"
    networks:
      - fairway-app-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

networks:
  fairway-app-network:
    external: false
    driver: bridge

volumes:
  redis_data:
  backend_logs:
  feedback_data:
  celery_logs:
