services:
  redis_server:
    build:
      context: .
      dockerfile: dockerfile_dev
      target: redis_prod
    image: fairway_redis
    container_name: fairway_redis_ct
    restart: unless-stopped
    hostname: redis
    volumes:
      # Direct bind read-only mount for config
      - ./redis.conf:/usr/local/etc/redis/redis.conf:ro
      # Named Mount for Data
      - redis_data:/data
    expose:
      - "6379"
    networks:
      - fairway-app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 8s
      retries: 10
      start_period: 4s

  backend:
    build:
      context: .
      dockerfile: dockerfile_dev
      target: backend
    image: fairway_backend
    container_name: fairway_backend_ct
    restart: unless-stopped
    volumes:
      - ./backend:/app
      - ./configs:/configs
      - backend_logs:/var/logs
      - feedback_data:/app/data
    depends_on:
      redis_server:
        condition: service_healthy
    env_file: "./backend/.env"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - fairway-app-network
    expose:
      - "8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      timeout: 15s
      retries: 5
      start_period: 6s
      interval: 45s

  # Celery Workers
  celery_workers:
    build:
      context: .
      dockerfile: dockerfile_dev
      target: celery
    image: fairway_celery_workers
    container_name: fairway_celery_ct
    restart: unless-stopped
    volumes:
      - ./backend:/app
      - ./configs:/configs
      - celery_logs:/var/logs
    depends_on:
      redis_server:
        condition: service_healthy
      backend:
        condition: service_healthy
    networks:
      - fairway-app-network

  # TODO: Handle this later on
  # flower:
  #   volumes:
  #     - ./backend:/app
  #   ports:
  #     - "5555:5555"
  #   depends_on:
  #     - redis_server
  #   command: ["celery", "-A", "celery_tasks.cel", "flower", "--loglevel=info"]

  # Frontend vuejs application
  frontend_server:
    build:
      context: .
      dockerfile: dockerfile_dev
      target: frontend_server
    image: fairway_frontend
    container_name: fairway_frontend_ct
    volumes:
      - ./configs:/configs
    depends_on:
      backend:
        condition: service_healthy
      redis_server:
        condition: service_healthy
      celery_workers:
        condition: service_started
    ports:
      - "80:80"
    networks:
      - fairway-app-network

networks:
  fairway-app-network:
    external: false
    driver: bridge

volumes:
  redis_data:
  backend_logs:
  feedback_data:
  celery_logs:
